-- CREATE TABLE questions (
--   id SERIAL PRIMARY KEY NOT NULL,
--   question text NOT NULL,
--   answer text NOT NULL,
--   lawyers_id INTEGER REFERENCES lawyers(id) ON DELETE CASCADE,
--   subject text NOT NULL 
-- );

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 1, 'If I have been involved in an auto accident, should I go to the doctor?', 'Probably. Immediately after an accident you should check to see if you have sustained any injuries. If you are not sure of the extent of your injuries it is best to go to the hospital. If you do not suspect you have any injuries, it is important that you watch for signs of injury for the next 12 hours as often pain from an accident doesn’t start until then. Contact your doctor immediately if you notice any pain.', 1, 'Traffic');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 2, 'What information should I document following an accident?', 'The specific location, date, and time of the accident. Names and contact information of all parties involved, including witnesses. Description of the vehicles involved and the injuries that were sustained. Insurance information for the other party (parties) involved in the accident.', 1, 'Traffic');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 3, 'What exactly is bankruptcy?', 'Bankruptcy is a federal court process that is designed to help both consumers and businesses either eliminate their debts (Chapter 7 bankruptcy) or repay their debts under the protection of bankruptcy court (Chapter 13 Bankruptcy).', 6, 'Bankruptcy');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 4, 'How does bankruptcy affect my credit?', 'The amount with which bankruptcy affects your credit depends mostly on how good your credit was before you filed for bankruptcy. If you have a high debt-to-asset ratio and are delinquent on accounts before you apply for bankruptcy, then your credit is already extremely poor. Ultimately, creditors do not like to see a bankruptcy listed on your credit report, and both Chapter 7 and Chapter 13 bankruptcies stay on your credit report for up to 10 years.', 6, 'Bankruptcy');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 5, 'Are you required to go to court if you breach a contract?', 'If you decide to breach a contract, whether or not you go to court depends on the other party. Occasionally, the other party won’t pursue a breach of contract; however, the option to take you to court is totally up to them. If you consult with a lawyer before you breach a contract, you will be well informed about the consequences if the other party chooses to pursue you for the breach of contract.', 2, 'Contract');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 6, 'What if a contract lawyer declines to take the case?', 'From time to time this happens. It may be because you don’t have a solid enough case against the party, or the attorney may have a conflict of interest that prevents them from taking the case. Find out specifically why they refused your case.', 2, 'Contract');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 7, 'Who pays the attorney fees for a breach of contract?', 'Usually, if you win the case, the party that breached the contract will be ordered to pay the attorney and court fees, unless the terms of the contract provide otherwise. However, you must be willing to pay the fees in case you fail to win your breach of contract case.', 2, 'Contract');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 8, 'How is sentencing for a criminal offense decided?', 'The three factors that generally influence sentencing are the type of crime for which you’ve been convicted, the sentencing guidelines and statutory recommendations for the crime, and your criminal history.', 7, 'Criminal Law');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 9, 'What are Miranda rights?', 'The Miranda rights are the rights that a person being accused of a crime has during police questioning and they include the right to remain silence and the right to an attorney. If you cannot afford an attorney then an attorney must be provided free of charge.', 7, 'Criminal Law');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 10, 'How do I find out if there is a warrant for my arrest?', 'If you are concerned about a potential criminal charge you should call a professional bondsman in your state and ask them to find out information about a possible warrant.', 7, 'Criminal Law');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 11, 'What exactly is identity theft?', 'Identity theft is a form of stealing someone’s identity, where someone pretends to be someone else by assuming that person’s identity. Most commonly, identities are taken in order to obtain credit, credit cards, steal money, apply for loans, establish accounts, or obtain a job.', 7, 'Identity Theft & Fraud');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 12, 'What should I do once I become aware of my identity being stolen?', 'As soon as you are aware of the fraud you should immediately contact the three major credit reporting agencies (Equifax, TransUnion, and Experian) to put a fraud alert on your credit profile.', 7, 'Identity Theft & Fraud');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 13, 'What rights do I have as a victim of identity theft?', 'The Fair Credit Reporting Act (FCRA) gives you specific rights when you are a victim or a potential victim of identity theft. Additionally, your credit cards and bank accounts often have options such as setting up fraud alerts and security freezes. It’s best to contact your financial institutions immediately upon suspicion of identity theft or fraud.', 7, 'Identity Theft & Fraud');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 14, 'How long does the bankruptcy process take?', 'Chapter 7 bankruptcy (the most common type of personal bankruptcy) typically takes 4 – 6 months. Chapter 13 bankruptcy, on the other hand, usually takes 3 – 5 years.', 6, 'Bankruptcy');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 15, 'Can a bankruptcy stop creditors from calling me?', 'Once a creditor is made aware that you have filed for bankruptcy, they must immediately cease all collection efforts. Once you have filed your bankruptcy petition, you can either wait the few weeks until the court mails the notice out to your creditors or you can directly contact your creditors and provide them with your case number.', 6, 'Bankruptcy');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 16, 'Will I have to go to court if I file for bankruptcy?', 'Yes. Approximately 30-40 days after you have filed the bankruptcy petition you will be required to attend a hearing, referred to as the First Meeting of Creditors. After this initial meeting you usually are not required to return to court unless a creditor or United States Trustee files a motion or adversary action.', 6, 'Bankruptcy');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 17, 'If the accident was my fault, should I say so?', 'It is best not to volunteer any opinion in regards to whose fault the accident was and to talk to a lawyer and to your insurance company before taking any blame. Anything you say to the other party involved in the accident or to the police can be used against you at a later time.', 1, 'Traffic');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 18, 'Does custody always go to just one parent?', 'No. Courts frequently award “joint custody,” which is at least partial custody to both parents. Some states are required to award joint custody except for cases where the children’s best interests, health, or safety would be compromised.', 4, 'Family');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 19, 'Are courts more likely to award custody to mothers than to fathers?', 'No state requires that a child custody be awarded to the mother without looking at the fitness of both parents. The majority of states require their courts to determine custody based on what is in the best interest of the child, without regard to the parent’s gender.', 4, 'Family');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 20, 'How do we transfer child custody without a lawyer?', 'You need to draw up an agreement between you and the child’s other parent and present this agreement to a local court for a judge to approve it. The agreement does not have to be in formal legal jargon but it does need to have the most important points included in it and also needs to be signed in front of a notary public.', 4, 'Family');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 21, 'How much does it cost to file for divorce?', 'The filing fee for a divorce petition is usually between $100 and $350 in most states. To file a response to a divorce petition, it costs an additional $100 and $200.', 4, 'Family');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 22, 'Will I have to go to court during my divorce?', 'You may not have to go to court if the divorce is uncontested and a marital settlement agreement is filed. However, it is always possible that the court could request a hearing (formal or informal).', 4, 'Family');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 23, 'Who receives custody of children in a divorce?', 'This decision is up to the parents themselves, if they can come to an agreement on custody. If parents in a child custody dispute are not able to negotiate an agreement, the custody decision is made by a family court judge. The factors that influence the judge’s decision include what is in the child’s “best interests,” which parents has been the child’s “primary caretaker,” and the child’s preference (if they are old enough).', 4, 'Famiy');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 24, 'Will I go to jail if I am convicted of a DUI?', 'Although DUI laws vary greatly from state to state, most states do not require jail time for a first DUI offense. However, almost all states require jail time for a second DUI.', 1, 'Driving Under Influence');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 25, 'Will I lose my license because of a DUI?', 'In the majority of DUI cases, you will lose your driving privilege at least temporarily. If you are a first time offender, you will likely get your driving privileges restored after approximately 90 days. If you have prior DUI convictions you could potentially have your license suspended for at least one year or possibly revoked.', 1, 'Driving Under Influence');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 26, 'How long will a DUI stay on my record?', 'You can count on a DUI staying on your record for at least 5 years, but the laws for this vary by state. In some states, having any prior DUI conviction on your record can affect your sentencing, no matter how many years have passed.', 1, 'Driving Under Influence');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 27, 'Is a DUI considered a felony?', 'A first time DUI offense is usually charged as a misdemeanor, rather than a felony. However if your DUI was related to an accident that caused someone to be injured, the charge could be raised to a felony.', 1, 'Driving Under Influence');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 28, 'Must I claim a dependent to qualify for head of household filing status?', 'In some circumstances you do not have to claim a child as dependent in order to qualify for head of household filing status. An example would be a custodial parent might be able to claim head of household filing status even if that parent released a claim to exemption for the child.', 6, 'IRS');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 29, 'What is a split refund?', 'A split refund allows you to divide your refund in any manner you chose and have that refund directly deposited to up to three different accounts with U.S. financial institutions. You should use Form 8888 (Allocation of Refund) to have your refund split.', 6, 'IRS');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 30, 'What is Earned Income Tax Credit (EITC)?', 'Earned Income Tax Credit is a refundable credit that is available to certain individuals and families with low to moderate levels of earned income. To qualify for EITC, you must meet certain requirements and file a tax return, even if you do not owe any taxes.', 6, 'IRS');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 31, 'What is the Fair Labor Standards Act (FLSA)?', 'The FLSA establishes standards for full-time and part-time employees in the private sector as well as in Federal, State, and local governments. These standards include minimum wage, overtime pay, recordkeeping, and child labor.', 5, 'Labor & Employment');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 32, 'If I become pregnant can my employer fire or reassign me?', 'Under the Civil Rights act of 1964 an employer who has 15 or more employees cannot fire you because you are pregnant. In addition, your employer must permit you to continue working for as long as you are able. There are some states with laws that cover employers with less than 15 employees, and that information is available via the Women’s Bureau Office.', 5, 'Labor & Employment');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 33, 'Is additional pay required if I work at nights or on weekends?', 'Additional pay is a matter of agreement between the employer and the employee. Although the FLSA does not require additional pay for weekend or night work, it does require that covered, nonexempt employees be paid no less than time and a half of the employee’s regular rate if they work more than 40 hours in a workweek.', 5, 'Labor & Employment');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 34, 'What is a Lemon?', 'In a nutshell, any defect or nonconformity, or combination of defects, which is/are not repaired within a reasonable number of attempts or a reasonable amount of time, may entitle you to Lemon Law relief. Your vehicle does NOT have to be breaking down to be considered a lemon. In short, if you are aggravated enough to be reading this you may have a lemon. All states differ so you should consult with an attorney experienced in lemon law to determine your rights.', 5, 'Lemon Law');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 35, 'What Types Of Products Are Covered By Lemon Law?', 'Almost any type of passenger vehicle is covered by the Lemon Law. This means that cars, trucks, vans, motorcycles and many other types of motor vehicles are usually covered under the Lemon Law. For boats, ATVs, RVs and items that may not covered by the strict definitions of the State Lemon Law, other State and Federal Lemon Laws are available which do cover these products.', 5, 'Lemon Law');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 36, 'How Long Do I Have To Bring A Lemon Law Claim?', 'There is a misconception that you must bring your case within a very short period of time because some State Lemon Laws require that you first report the problem within a certain period after the delivery of the vehicle to you (sometimes known as the “Presumption Period” or “Repair Period”). However, this does not mean you have to bring your lawsuit within that time frame, although the sooner you do so the better in most instances.', 5, 'Lemon Law');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 37, 'What is personal injury?', 'Personal injury is defined as physical or psychological injury that is caused by another party. This individual or company may have acted intentionally or negligently or may be held strictly liable for causing injury to another person.', 3, 'Injury');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 38, 'What are the most common kinds of personal injury cases?', 'The most common kinds of personal injury cases are road traffic accidents, assault claims, accidents at work or at home, tripping accidents, and product liability claims.', 3, 'Injury');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 39, 'What is the difference between compensatory and punitive damages?', 'Compensatory damages include money for medical care, lost wages, and pain and suffering. Punitive damages are to penalize the defendant and whether or not punitive damages will be ordered varies depending on the particular case and the state laws.', 3, 'Injury');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 40, 'What is a tax?', 'A tax is a financial charge that is imposed upon an individual of legal entity. Taxation is defined as the governmental assessment of property value, income, transactions, estates, and duties on imports from foreign countries. Primary taxation issues most frequently include taxes on income and taxes on wealth or estates. There are two ways to pay taxes; indirectly and directly. An example of an indirectly paid tax would be when you buy coffee at a local store, the retailer charges you tax on that coffee which is then subsequently paid to the government. Examples of directly paid taxes would be the taxes you pay on your land, property, or income.', 6, 'Tax');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 41, 'What is income tax?', 'Income tax is a government tax that is imposed on individuals (taxpayers) and income tax varies with the income (profits) of the taxpayer. Details can vary widely by jurisdiction and each state has their own income tax website. Income tax is usually calculated as the product of a tax rate multiplied by the taxpayer’s taxable income. Taxable income usually only includes net gain and credits, such as donations to charity, can be allowed to reduce tax. If you are to pay your taxes late, you are subject to significant penalties including fines and jail time, so securing legal assistance is strongly recommended', 6, 'Tax');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 42, 'What is property tax?', 'Property tax is tax on property (land, house automobile, etc.) that the owner of that property is required to pay. Depending on the governing authority, property tax can be paid to a national government, a federated state, a municipality, or a country. Rent ant mortgage tax, on the other hand, is paid based on the percentage of the rent or mortgage value. The four broad types of property include land, improvements to land (immovable man-made objects, ex: buildings), personal property (movable man-made objects), and intangible property. The term “real property,” or “real estate,” refers to the combination of land and improvements.', 6, 'Tax');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 43, 'What is payroll tax?', 'Payroll tax is a tax that is imposed on employers and employees. Payroll tax is usually calculated as a percentage of the salaries that employers pay to their employees and generally falls into two categories. These two payroll tax categories are deductions from an employee’s wages and taxes that are paid by the employer based on the employee’s wages. Deductions from an employee’s wages are taxes that employers are required to withhold, whereas taxes that are paid by the employer based on the employee’s wages are paid from the employer’s own funds. Ultimately, the burden of payroll tax falls on the employee, as the employer’s share of payroll taxes is passed onto employees.', 6, 'Tax');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 44, 'What is estate tax?', 'Estate tax is a tax that is imposed on the transfer of the taxable estate of someone who is deceased, usually in the form of an inheritance. For more information on estate planning or for information on the preparation of wills, estates, and/or trusts, see our associated webpages.', 6, 'Tax');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 45, 'What does “reasonable visitation” mean?', '“Reasonable visitation” is usually ordered by a court when determining the visitation rights of a noncustodial parent. This allows the parents the flexibility to work out their own schedule or time and place.', 5, 'Visitation Rights');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 46, 'Does the court decide the visitation schedule?', 'If the two parents can agree on a parenting plan and visitation schedule you can submit it to the court for approval. It’s a good idea to put a provision in the agreement that states that as long as you write down changes and you both sign off on them, they are enforceable just like the original court-approved order.', 5, 'Visitation Rights');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 47, 'Are grandparents entitled to visitation?', 'All 50 states have a “grandparent visitation” statute in which grandparents can ask the court to grand them the legal right to maintain their relationship(s) with their grandchildren. The specific details of such visitations vary greatly by state, and all courts give preference to the parent’s wishes in regards to grandparent visitations.', 5, 'Visitation Rights');

INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 48, 'What happens if a person dies without a last will?', 'When a person passes away who does not have a last will, that person’s assets are distributed according to the laws of the state, not necessarily according to their wishes. Each state has different laws, but usually money and other assets pass to the deceased person’s spouse.', 5, 'Wills & Estates');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 49, 'What is the difference between a living will and a last will?', 'The purpose of a living will is to provide healthcare instructions in advance (such as whether or not life support is desired), whereas the purpose of a last will is to distribute assets after a person’s death.', 5, 'Wills & Estates');
INSERT INTO questions (id, question, answer, lawyers_id, subject) VALUES ( 50, 'What is a Power of Attorney?', 'A Power of Attorney (POA) is a legally enforceable document in which you can authorize another person(s) to act on your behalf in the event that you are unable to do so.', 5, 'Wills & Estates');








